apiVersion: v2
name: ke-use-nfs-server-sidecar-fluentbit
description: A Helm chart for on-premise Kubernetes with NFS server and FluentBit sidecar
type: application
version: 0.1.0
appVersion: "0.1.0"
