repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: external-dns
    namespace: luckyday
    createNamespace: true
    chart: external-dns/external-dns
    version: 1.18.0
    values:
      - values/mgmt.yaml
