{{- if .Values.imagePullSecretCreate.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretCreate.name }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecretCreate.dockerconfigjson | quote }}
{{- end }}

