{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}
  namespace: {{ .Release.Namespace }}
rules:
{{- range .Values.rbac.role.resources }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
    resources: {{ .resources | toYaml | nindent 4 }}
    verbs: {{ .verbs | toYaml | nindent 4 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBinding.name }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "ke-use-nfs-server.fullname" .) .Values.rbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

