# apiversion
apiVersion: metallb.io/v1beta1 
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  # Using ip address pool
  - 111.111.111.111 - 111.111.111.111 
  autoAssign: true
--- 
apiVersion: metallb.io/v1beta1 
# Use l2 mode
kind: L2Advertisement 
metadata:
  name: l2-network
  namespace: metallb-system
spec:
   # ipAddressPools
  ipAddressPools:
    - ip-pool
