global:
  image:
    # -- Registry host to pull images from.
    registry: registry.k8s.io
controller:
  ingressClassResource:
    name: nginx-public  # IngressClass Name
    enabled: true
    default: false     # Default IngressClass
    controllerValue: "k8s.io/ingress-nginx-public"  # IngressClass Controller Value
  service:
    # -- Enable controller services or not. This does not influence the creation of either the admission webhook or the metrics service.
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "" # LoadBalancer IP
