{{- range $externalSecret := .Values.externalSecrets }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  namespace: {{ $externalSecret.namespace }}
spec:
  backendType: {{ $externalSecret.backendType }}
  data:
    {{- range $data := $externalSecret.datas }}
    - key: {{ $data.key }}
      property: {{ $data.property }}
      name: {{ $data.name }}
    {{- end }}
---
{{- end }}
