apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "somaz.fullname" . }}
spec:
  healthCheck:
    checkIntervalSec: {{ .Values.backendConfig.healthCheck.checkIntervalSec }}
    timeoutSec: {{ .Values.backendConfig.healthCheck.timeoutSec }}
    healthyThreshold: {{ .Values.backendConfig.healthCheck.healthyThreshold }}
    unhealthyThreshold: {{ .Values.backendConfig.healthCheck.unhealthyThreshold }}
    type: {{ .Values.backendConfig.healthCheck.type }}
    requestPath: {{ .Values.backendConfig.healthCheck.requestPath }}
    port: {{ .Values.backendConfig.healthCheck.port }}
  {{- if .Values.backendConfig.customRequestHeaders }}
  customRequestHeaders:
    {{- toYaml .Values.backendConfig.customRequestHeaders | nindent 4 }}
  {{- end }}


