{{- range $storageClass := .Values.storageClasses }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $storageClass.name }}
provisioner: {{ $storageClass.provisioner }}
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
volumeBindingMode: {{ $storageClass.volumeBindingMode }}
---
{{- end }}