apiVersion: v1
kind: Service
metadata:
  name: {{ include "somaz.fullname" . }}
  labels:
    {{- include "somaz.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{{ .Values.service.backendConfig | toJson }}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "somaz.selectorLabels" . | nindent 4 }}
