{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ke-use-nfs-server-sidecar-fluentbit.serviceAccountName" . }}
  labels:
    {{- include "ke-use-nfs-server-sidecar-fluentbit.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
