apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-appicationset
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: somaz-eks
                  url: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sk1.ap-northeast-2.eks.amazonaws.com # EKS url
                  values:
                    environment: dev1
                    project: somaz-aws
                - cluster: somaz-eks
                  url: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sk1.ap-northeast-2.eks.amazonaws.com # EKS url
                  values:
                    environment: dev2
                    project: somaz-aws
          - git:
              repoURL: git@github.com:somaz94/helm-chart-template.git
              revision: HEAD
              directories:
                - path: aws/eks_fargate_use_efs/* # path
              # refreshInterval: 180s # default is 180s
  template:
    metadata:
      name: '{{values.environment}}-{{values.project}}-{{path.basename}}'
      labels:
        environment: '{{values.environment}}'
        project: '{{values.project}}'
        app-name: '{{path.basename}}'
    spec:
      project: '{{cluster}}'
      source:
        repoURL: git@github.com:somaz94/helm-chart-template.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          version: v3
          valueFiles:
            - '{{path.basename}}.values.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{values.environment}}-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

