apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gcp-externalsecrets-appicationset
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: somaz-gke
                  url: https://1.1.1.1 # ClusterIP
                  values:
                    namespace: external-secrets
                    environment: somaz
                    project: somaz
          - git:
              repoURL: git@github.com:somaz94/helm-chart-template.git
              revision: HEAD
              directories:
                - path: gcp/external-secrets/* # Path
              # refreshInterval: 180s # default is 180s
  template:
    metadata:
      name: '{{values.environment}}-{{values.project}}-{{path.basename}}' # '{{cluster}}-{{path.basename}}'
    spec:
      project: '{{cluster}}'
      source:
        repoURL: git@github.com:somaz94/helm-chart-template.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          version: v3
          valueFiles:
            - '{{values.environment}}.values.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{values.namespace}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

