apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onpremise-appicationset
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: master-node.somaz.link # your cluster name
                  url: https://xx.xx.xxx.xx:6443  # your cluster url
                  values:
                    project: somaz-onpremise
                    environment: dev1
          - git:
              repoURL: git@github.com:somaz94/helm-chart-template.git # your source repo
              revision: HEAD
              directories:
                - path: onpremise/ke-use-nfs-server/*
              # refreshInterval: 180s # default is 180s
  template:
    metadata:
      name: '{{values.environment}}-{{values.project}}-{{path.basename}}'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: git@github.com:somaz94/helm-chart-template.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          version: v3
          valueFiles:
            - '{{path.basename}}.values.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{values.project}}-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # preserveResourcesOnDeletion: false # default is true 
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true


