{{- range $persistentVolume := .Values.persistentVolumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $persistentVolume.name }}
spec:
  capacity:
    storage: {{ $persistentVolume.storage }}
  volumeMode: {{ $persistentVolume.volumeMode }}
  {{ with $persistentVolume.accessModes }}
  accessModes:
    {{- toYaml . | nindent 8 }}
  {{ end }}
  persistentVolumeReclaimPolicy: {{ $persistentVolume.reclaimPolicy }}
  storageClassName: {{ $persistentVolume.storageClassName }}
  csi:
    driver: {{ $persistentVolume.driver }}
    volumeHandle: {{ $persistentVolume.volumeHandle }}
---
{{- end }}