apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "gke-use-nfs-server.fullname" . }}
spec:
  redirectToHttps:
    enabled: {{ .Values.frontendConfig.redirectToHttpsEnabled }}
