apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "haproxy.fullname" . }}
spec:
  domains:
  {{- range .Values.managedCertificate.domains }}
    - {{ . }}
  {{- end }}
{{- if .Values.hasStaging }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "haproxy.fullname" . }}
  namespace: "staging-{{ .Values.namespace }}"
spec:
  domains:
  {{- range .Values.managedCertificate.domains }}
    - {{ . }}
  {{- end }}
{{- end}}
