apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{{ .Values.service.backendConfig | toJson }}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}
---
{{- if .Values.hasStaging }}
apiVersion: v1
kind: Service
metadata:
  namespace: "staging-{{ .Values.namespace }}"
  name: "staging-{{ include "haproxy.fullname" . }}"
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{{ .Values.service.backendConfig | toJson }}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "staging-{{ .Values.fullnameOverride }}"
{{- end }}
