environments:
  default:
    values:
      - values/mgmt.yaml
  mgmt:
    values:
      - values/mgmt.yaml
  mgmt-nopath:
    values:
      - values/mgmt-nopath.yaml
  mgmt-annotations:
    values:
      - values/mgmt-annotations.yaml

---

repositories:
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

releases:
  - name: nfs-provisioner
    namespace: nfs-provisioner
    createNamespace: true   
    # chart: ./ # Use local chart directory 
    # Use the Remote chart repository nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - values/mgmt.yaml
    labels:
      environment: mgmt

  - name: nfs-provisioner-nopath
    namespace: nfs-provisioner
    createNamespace: true
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - values/mgmt-nopath.yaml
    labels:
      environment: mgmt-nopath

  - name: nfs-provisioner-ano
    namespace: nfs-provisioner
    createNamespace: true
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - values/mgmt-annotations.yaml
    labels:
      environment: mgmt-annotations

# helmDefaults:
#   wait: true
#   timeout: 300
#   atomic: true
#   cleanupOnFail: true

# Hooks to ensure proper installation and upgrades
hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "create"
      - "namespace"
      - "nfs-provisioner"
      - "--dry-run=client"
      - "-o"
      - "yaml"
      - "||"
      - "true" 

